source 'https://github.com/CocoaPods/Specs.git'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

$RNFirebaseAnalyticsWithoutAdIdSupport = true

target 'EasyONGApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-view-shot', :path => '../node_modules/react-native-view-shot'



  target 'EasyONGAppTests' do
    inherit! :complete
  end

  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end
